# Generated by Django 5.0.3 on 2024-04-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedlocations',
            name='hotel_id',
        ),
        migrations.RemoveField(
            model_name='likedlocations',
            name='restaurant_id',
        ),
        migrations.AddField(
            model_name='likedlocations',
            name='category_icon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='likedlocations',
            name='destination_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='likedlocations',
            name='photo_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='likedlocations',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='likedlocations',
            name='locality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='likedlocations',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
