# Generated by Django 5.0.3 on 2024-07-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
