# Generated by Django 5.0.3 on 2024-06-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
