# Generated by Django 5.0.3 on 2024-06-13 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_plan_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('summary', models.CharField(max_length=512, null=True)),
                ('day', models.IntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.plan')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=512, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=512, null=True)),
                ('start_hour', models.CharField(max_length=50, null=True)),
                ('end_hour', models.CharField(max_length=50, null=True)),
                ('day', models.IntegerField(null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.itinerary')),
            ],
        ),
    ]
