# Generated by Django 5.0.3 on 2024-07-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_plan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='summary',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
