# Generated by Django 5.0.3 on 2024-07-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_likeplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeplan',
            name='id_plan',
            field=models.IntegerField(null=True),
        ),
    ]
