# Generated by Django 5.0.3 on 2024-03-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('addr_city', models.CharField(max_length=255)),
                ('addr_country', models.CharField(max_length=10)),
                ('addr_street', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=50)),
            ],
        ),
    ]
