# Generated by Django 5.0.3 on 2024-03-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_feature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tourism',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
