# Generated by Django 5.0.3 on 2024-03-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_feature', '0002_hotel_tourism'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='contact_email',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='addr_country',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='addr_street',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='brand',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='contact_phone',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
