# Generated by Django 5.0.3 on 2024-03-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_feature', '0005_remove_hotel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
