# Generated by Django 5.0.3 on 2024-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_feature', '0006_alter_hotel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
