# Generated by Django 5.0.3 on 2024-03-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_feature', '0007_alter_hotel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('amenity', models.CharField(max_length=50)),
                ('cuisine', models.CharField(default=None, max_length=100, null=True)),
                ('addr_city', models.CharField(max_length=255)),
                ('addr_country', models.CharField(default=None, max_length=10, null=True)),
                ('addr_street', models.CharField(default=None, max_length=255, null=True)),
                ('contact_phone', models.CharField(default=None, max_length=255, null=True)),
                ('contact_email', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
