# Generated by Django 5.0.3 on 2024-03-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_feature', '0008_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='long',
            new_name='lon',
        ),
    ]
