# Generated by Django 5.0.3 on 2024-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_feature', '0009_rename_long_restaurant_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
