# Generated by Django 5.0.3 on 2024-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_feature', '0010_alter_restaurant_cuisine'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDestinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsq_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('destination_category', models.CharField(max_length=255)),
                ('category_icon', models.CharField(max_length=255)),
                ('photo_url', models.CharField(max_length=255)),
            ],
        ),
    ]
