# Generated by Django 5.0.3 on 2024-04-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_feature', '0012_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='populardestinations',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='populardestinations',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
