# Generated by Django 5.0.3 on 2024-05-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_feature', '0014_review_replyreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='destiation_id',
            new_name='destination_id',
        ),
    ]
